<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="YY524559" failures="1" tests="8" name="Application" time="0.115" errors="0" timestamp="2020-04-14T19:20:27 IST">
  <testcase classname="com.examples.Registration" name="signUp" time="0.018"/>
  <testcase classname="com.examples.Applications" name="doLogin" time="0.015"/>
  <testcase classname="com.examples.LoginTest" name="testDifferent" time="0.02"/>
  <testcase classname="com.examples.Registration" name="register" time="0.001"/>
  <testcase classname="com.examples.Applications" name="doLogout" time="0.007"/>
  <testcase classname="com.examples.LoginTest" name="testDifferent" time="0.01"/>
  <testcase classname="com.examples.Applications" name="doPasswordChange" time="0.006">
    <failure type="java.lang.AssertionError" message="Passed expected [Alhaam1] but found [Alhaam]">
      <![CDATA[java.lang.AssertionError: Passed expected [Alhaam1] but found [Alhaam]
at com.examples.Applications.doPasswordChange(Applications.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- doPasswordChange -->
  <testcase classname="com.examples.LoginTest" name="testDifferent" time="0.01"/>
</testsuite> <!-- Application -->
